[package]

name = "gif"
license = "MIT"
version = "0.0.2"
authors = ["nwin <nwin@users.noreply.github.com>"]

[lib]
name = "gif"
crate-type = ["dylib", "rlib"]

[dependencies]
lzw = "0.4"

[dev-dependencies.image]
image = "0.3.7"

[features]
default = ["c_api"]

c_api = []
